### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by c01nd01r** [AndreySamokhvalov/HeadHunterAutoUpdate#1]
Куки с файл txt файл вставил. При запуске кидает:

Traceback (most recent call last):
  File "autoUpdate.py", line 34, in <module>
    job_update(jobIdFileName)
  File "autoUpdate.py", line 28, in job_update
    jobDictionary = json.load(content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 5 column 2 (char 84)

**Comment by avemeva** [comment]
Привет, эта проблемка обычно выскакивать когда json библиотека не может справиться с файлом. У меня получилось воспроизвести проблему, но потом каким-то чудом она исчезла, но это не суть, после того как у меня получилось запустить скрипт, я понял, что на hh.ru сделали что-то по типу защиты против мошенничества, я думаю обойти её не сложно, просто сейчас к сожалению нету времени этим заниматься.

**Comment by c01nd01r** [comment]
Понятно.
Оказывается, у них есть API, можно работать с ним для обновления резюме. Попробую написать скрипт на nodejs.
Ну ладно, в общем спасибо.
